/* DO NOT EDIT THIS FILE - it is machine generated */

#include "JNIConverter.h"

#ifndef _Included_$$packageId$$_$$projectName$$Sdk
#define _Included_$$packageId$$_$$projectName$$Sdk
#ifdef __cplusplus
extern "C" {
#endif
    JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved);

    /*
    * Class:     com_seewo_hello_HelloSdk
    * Method:    hello
    * Signature: ()V
    */
    JNIEXPORT void JNICALL Java_$$packageId$$_$$projectName$$Sdk_hello
    (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
